export const EXERCISE_LIST = [
  "Squat",
  "Bench Press",
  "Deadlift",
  "Overhead Press",
  "Barbell Row",
  "Pull Up",
  "Push Up",
  "Chin Up",
  "Dips",
  "Leg Press",
  "Leg Curl",
  "Leg Extension",
  "Lunge",
  "Dumbbell Press",
  "Incline Press",
  "Dumbbell Fly",
  "Cable Crossover",
  "Lat Pulldown",
  "Seated Row",
  "Lateral Raise",
  "Front Raise",
  "Shoulder Press",
  "Barbell Curl",
  "Dumbbell Curl",
  "Tricep Extension",
  "Tricep Pushdown",
] as const;

export type ExerciseName = (typeof EXERCISE_LIST)[number];
